[2024-07-19 12:33:20 +0300] [5009] [INFO] Starting gunicorn 20.1.0
[2024-07-19 12:33:20 +0300] [5009] [INFO] Listening at: http://127.0.0.1:8080 (5009)
[2024-07-19 12:33:20 +0300] [5009] [INFO] Using worker: eventlet
[2024-07-19 12:33:20 +0300] [5010] [INFO] Booting worker with pid: 5010
[2024-07-19 12:33:20 +0300] [5010] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'webapp.v1'
[2024-07-19 12:33:20 +0300] [5010] [INFO] Worker exiting (pid: 5010)
[2024-07-19 12:33:20 +0300] [5009] [INFO] Shutting down: Master
[2024-07-19 12:33:20 +0300] [5009] [INFO] Reason: Worker failed to boot.
[2024-07-19 12:33:47 +0300] [5027] [INFO] Starting gunicorn 20.1.0
[2024-07-19 12:33:47 +0300] [5027] [INFO] Listening at: http://127.0.0.1:8080 (5027)
[2024-07-19 12:33:47 +0300] [5027] [INFO] Using worker: eventlet
[2024-07-19 12:33:47 +0300] [5028] [INFO] Booting worker with pid: 5028
[2024-07-19 12:33:47 +0300] [5028] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/geventlet.py", line 143, in init_process
    super().init_process()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 384, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'webapp.v1'
[2024-07-19 12:33:47 +0300] [5028] [INFO] Worker exiting (pid: 5028)
[2024-07-19 12:33:47 +0300] [5027] [INFO] Shutting down: Master
[2024-07-19 12:33:47 +0300] [5027] [INFO] Reason: Worker failed to boot.
[2024-07-19 16:44:30 +0300] [10101] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:44:30 +0300] [10101] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:44:30 +0300] [10101] [ERROR] Retrying in 1 second.
[2024-07-19 16:44:31 +0300] [10101] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:44:31 +0300] [10101] [ERROR] Retrying in 1 second.
[2024-07-19 16:44:32 +0300] [10101] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:44:32 +0300] [10101] [ERROR] Retrying in 1 second.
[2024-07-19 16:44:33 +0300] [10101] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:44:33 +0300] [10101] [ERROR] Retrying in 1 second.
[2024-07-19 16:44:34 +0300] [10101] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:44:34 +0300] [10101] [ERROR] Retrying in 1 second.
[2024-07-19 16:44:35 +0300] [10101] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 16:45:45 +0300] [10158] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:45:45 +0300] [10158] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:45:45 +0300] [10158] [ERROR] Retrying in 1 second.
[2024-07-19 16:45:46 +0300] [10158] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:45:46 +0300] [10158] [ERROR] Retrying in 1 second.
[2024-07-19 16:45:47 +0300] [10158] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:45:47 +0300] [10158] [ERROR] Retrying in 1 second.
[2024-07-19 16:45:48 +0300] [10158] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:45:48 +0300] [10158] [ERROR] Retrying in 1 second.
[2024-07-19 16:45:49 +0300] [10158] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:45:49 +0300] [10158] [ERROR] Retrying in 1 second.
[2024-07-19 16:45:50 +0300] [10158] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 16:51:56 +0300] [10316] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:51:56 +0300] [10316] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:51:56 +0300] [10316] [ERROR] Retrying in 1 second.
[2024-07-19 16:51:57 +0300] [10316] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:51:57 +0300] [10316] [ERROR] Retrying in 1 second.
[2024-07-19 16:51:58 +0300] [10316] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:51:58 +0300] [10316] [ERROR] Retrying in 1 second.
[2024-07-19 16:51:59 +0300] [10316] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:51:59 +0300] [10316] [ERROR] Retrying in 1 second.
[2024-07-19 16:52:00 +0300] [10316] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:52:00 +0300] [10316] [ERROR] Retrying in 1 second.
[2024-07-19 16:52:01 +0300] [10316] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 16:57:51 +0300] [10486] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:57:51 +0300] [10486] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:57:51 +0300] [10486] [ERROR] Retrying in 1 second.
[2024-07-19 16:57:52 +0300] [10486] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:57:52 +0300] [10486] [ERROR] Retrying in 1 second.
[2024-07-19 16:57:53 +0300] [10486] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:57:53 +0300] [10486] [ERROR] Retrying in 1 second.
[2024-07-19 16:57:54 +0300] [10486] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:57:54 +0300] [10486] [ERROR] Retrying in 1 second.
[2024-07-19 16:57:55 +0300] [10486] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:57:55 +0300] [10486] [ERROR] Retrying in 1 second.
[2024-07-19 16:57:56 +0300] [10486] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 16:58:01 +0300] [10504] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:58:01 +0300] [10504] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:58:01 +0300] [10504] [ERROR] Retrying in 1 second.
[2024-07-19 16:58:02 +0300] [10504] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:58:02 +0300] [10504] [ERROR] Retrying in 1 second.
[2024-07-19 16:58:03 +0300] [10504] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:58:03 +0300] [10504] [ERROR] Retrying in 1 second.
[2024-07-19 16:58:04 +0300] [10504] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:58:04 +0300] [10504] [ERROR] Retrying in 1 second.
[2024-07-19 16:58:05 +0300] [10504] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:58:05 +0300] [10504] [ERROR] Retrying in 1 second.
[2024-07-19 16:58:06 +0300] [10504] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 16:59:44 +0300] [10569] [INFO] Starting gunicorn 20.1.0
[2024-07-19 16:59:44 +0300] [10569] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:59:44 +0300] [10569] [ERROR] Retrying in 1 second.
[2024-07-19 16:59:45 +0300] [10569] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:59:45 +0300] [10569] [ERROR] Retrying in 1 second.
[2024-07-19 16:59:46 +0300] [10569] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:59:46 +0300] [10569] [ERROR] Retrying in 1 second.
[2024-07-19 16:59:47 +0300] [10569] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:59:47 +0300] [10569] [ERROR] Retrying in 1 second.
[2024-07-19 16:59:48 +0300] [10569] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2024-07-19 16:59:48 +0300] [10569] [ERROR] Retrying in 1 second.
[2024-07-19 16:59:49 +0300] [10569] [ERROR] Can't connect to ('127.0.0.1', 8080)
[2024-07-19 17:02:46 +0300] [10676] [INFO] Starting gunicorn 20.1.0
[2024-07-19 17:02:46 +0300] [10676] [INFO] Listening at: http://127.0.0.1:8081 (10676)
[2024-07-19 17:02:46 +0300] [10676] [INFO] Using worker: eventlet
[2024-07-19 17:02:46 +0300] [10677] [INFO] Booting worker with pid: 10677
[2024-07-19 18:28:37 +0300] [5519] [INFO] Starting gunicorn 20.1.0
[2024-07-19 18:28:37 +0300] [5519] [INFO] Listening at: http://127.0.0.1:8081 (5519)
[2024-07-19 18:28:37 +0300] [5519] [INFO] Using worker: eventlet
[2024-07-19 18:28:37 +0300] [5520] [INFO] Booting worker with pid: 5520
